[package]
name = "i_04_1_variable_bindings_mutability"
version = "0.1.0"
authors = ["jcastells"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
